// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class Categories
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject categoriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.Categories";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Categories_Recipe("MainModule.Categories_Recipe");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Categories(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MainModule.Categories"));
	}

	protected Categories(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject categoriesMendixObject)
	{
		if (categoriesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MainModule.Categories", categoriesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MainModule.Categories");

		this.categoriesMendixObject = categoriesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Categories.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mainmodule.proxies.Categories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mainmodule.proxies.Categories.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mainmodule.proxies.Categories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.Categories(context, mendixObject);
	}

	public static mainmodule.proxies.Categories load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.Categories.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Categories_Recipe
	 */
	public final mainmodule.proxies.Recipe getCategories_Recipe() throws com.mendix.core.CoreException
	{
		return getCategories_Recipe(getContext());
	}

	/**
	 * @param context
	 * @return value of Categories_Recipe
	 */
	public final mainmodule.proxies.Recipe getCategories_Recipe(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Recipe result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Categories_Recipe.toString());
		if (identifier != null)
			result = mainmodule.proxies.Recipe.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Categories_Recipe
	 * @param categories_recipe
	 */
	public final void setCategories_Recipe(mainmodule.proxies.Recipe categories_recipe)
	{
		setCategories_Recipe(getContext(), categories_recipe);
	}

	/**
	 * Set value of Categories_Recipe
	 * @param context
	 * @param categories_recipe
	 */
	public final void setCategories_Recipe(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Recipe categories_recipe)
	{
		if (categories_recipe == null)
			getMendixObject().setValue(context, MemberNames.Categories_Recipe.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Categories_Recipe.toString(), categories_recipe.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return categoriesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.Categories that = (mainmodule.proxies.Categories) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MainModule.Categories";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
