// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class IngredientItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ingredientItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.IngredientItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quantity("Quantity"),
		Unit("Unit"),
		Content("Content"),
		IngredientItem_Items("MainModule.IngredientItem_Items");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IngredientItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MainModule.IngredientItem"));
	}

	protected IngredientItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingredientItemMendixObject)
	{
		if (ingredientItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MainModule.IngredientItem", ingredientItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MainModule.IngredientItem");

		this.ingredientItemMendixObject = ingredientItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'IngredientItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mainmodule.proxies.IngredientItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mainmodule.proxies.IngredientItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mainmodule.proxies.IngredientItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.IngredientItem(context, mendixObject);
	}

	public static mainmodule.proxies.IngredientItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.IngredientItem.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.String quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of Unit
	 */
	public final java.lang.String getUnit()
	{
		return getUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit
	 */
	public final java.lang.String getUnit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit.toString());
	}

	/**
	 * Set value of Unit
	 * @param unit
	 */
	public final void setUnit(java.lang.String unit)
	{
		setUnit(getContext(), unit);
	}

	/**
	 * Set value of Unit
	 * @param context
	 * @param unit
	 */
	public final void setUnit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit)
	{
		getMendixObject().setValue(context, MemberNames.Unit.toString(), unit);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of IngredientItem_Items
	 */
	public final mainmodule.proxies.Items getIngredientItem_Items() throws com.mendix.core.CoreException
	{
		return getIngredientItem_Items(getContext());
	}

	/**
	 * @param context
	 * @return value of IngredientItem_Items
	 */
	public final mainmodule.proxies.Items getIngredientItem_Items(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Items result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IngredientItem_Items.toString());
		if (identifier != null)
			result = mainmodule.proxies.Items.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IngredientItem_Items
	 * @param ingredientitem_items
	 */
	public final void setIngredientItem_Items(mainmodule.proxies.Items ingredientitem_items)
	{
		setIngredientItem_Items(getContext(), ingredientitem_items);
	}

	/**
	 * Set value of IngredientItem_Items
	 * @param context
	 * @param ingredientitem_items
	 */
	public final void setIngredientItem_Items(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Items ingredientitem_items)
	{
		if (ingredientitem_items == null)
			getMendixObject().setValue(context, MemberNames.IngredientItem_Items.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IngredientItem_Items.toString(), ingredientitem_items.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ingredientItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.IngredientItem that = (mainmodule.proxies.IngredientItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MainModule.IngredientItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
