// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class IngredientDivision
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ingredientDivisionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.IngredientDivision";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		IngredientDivision_Ingredients("MainModule.IngredientDivision_Ingredients"),
		Items_IngredientDivision("MainModule.Items_IngredientDivision");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MainModule.IngredientDivision"));
	}

	protected IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingredientDivisionMendixObject)
	{
		if (ingredientDivisionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MainModule.IngredientDivision", ingredientDivisionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MainModule.IngredientDivision");

		this.ingredientDivisionMendixObject = ingredientDivisionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'IngredientDivision.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mainmodule.proxies.IngredientDivision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mainmodule.proxies.IngredientDivision.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mainmodule.proxies.IngredientDivision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.IngredientDivision(context, mendixObject);
	}

	public static mainmodule.proxies.IngredientDivision load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.IngredientDivision.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of IngredientDivision_Ingredients
	 */
	public final mainmodule.proxies.Ingredients getIngredientDivision_Ingredients() throws com.mendix.core.CoreException
	{
		return getIngredientDivision_Ingredients(getContext());
	}

	/**
	 * @param context
	 * @return value of IngredientDivision_Ingredients
	 */
	public final mainmodule.proxies.Ingredients getIngredientDivision_Ingredients(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Ingredients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IngredientDivision_Ingredients.toString());
		if (identifier != null)
			result = mainmodule.proxies.Ingredients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IngredientDivision_Ingredients
	 * @param ingredientdivision_ingredients
	 */
	public final void setIngredientDivision_Ingredients(mainmodule.proxies.Ingredients ingredientdivision_ingredients)
	{
		setIngredientDivision_Ingredients(getContext(), ingredientdivision_ingredients);
	}

	/**
	 * Set value of IngredientDivision_Ingredients
	 * @param context
	 * @param ingredientdivision_ingredients
	 */
	public final void setIngredientDivision_Ingredients(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Ingredients ingredientdivision_ingredients)
	{
		if (ingredientdivision_ingredients == null)
			getMendixObject().setValue(context, MemberNames.IngredientDivision_Ingredients.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IngredientDivision_Ingredients.toString(), ingredientdivision_ingredients.getMendixObject().getId());
	}

	/**
	 * @return value of Items_IngredientDivision
	 */
	public final mainmodule.proxies.Items getItems_IngredientDivision() throws com.mendix.core.CoreException
	{
		return getItems_IngredientDivision(getContext());
	}

	/**
	 * @param context
	 * @return value of Items_IngredientDivision
	 */
	public final mainmodule.proxies.Items getItems_IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Items result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Items_IngredientDivision.toString());
		if (identifier != null)
			result = mainmodule.proxies.Items.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Items_IngredientDivision
	 * @param items_ingredientdivision
	 */
	public final void setItems_IngredientDivision(mainmodule.proxies.Items items_ingredientdivision)
	{
		setItems_IngredientDivision(getContext(), items_ingredientdivision);
	}

	/**
	 * Set value of Items_IngredientDivision
	 * @param context
	 * @param items_ingredientdivision
	 */
	public final void setItems_IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Items items_ingredientdivision)
	{
		if (items_ingredientdivision == null)
			getMendixObject().setValue(context, MemberNames.Items_IngredientDivision.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Items_IngredientDivision.toString(), items_ingredientdivision.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ingredientDivisionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.IngredientDivision that = (mainmodule.proxies.IngredientDivision) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MainModule.IngredientDivision";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
