// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class Items
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.Items";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Items_IngredientDivision("MainModule.Items_IngredientDivision");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Items(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MainModule.Items"));
	}

	protected Items(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject)
	{
		if (itemsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MainModule.Items", itemsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MainModule.Items");

		this.itemsMendixObject = itemsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Items.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mainmodule.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mainmodule.proxies.Items.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mainmodule.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.Items(context, mendixObject);
	}

	public static mainmodule.proxies.Items load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.Items.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Items_IngredientDivision
	 */
	public final mainmodule.proxies.IngredientDivision getItems_IngredientDivision() throws com.mendix.core.CoreException
	{
		return getItems_IngredientDivision(getContext());
	}

	/**
	 * @param context
	 * @return value of Items_IngredientDivision
	 */
	public final mainmodule.proxies.IngredientDivision getItems_IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.IngredientDivision result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Items_IngredientDivision.toString());
		if (identifier != null)
			result = mainmodule.proxies.IngredientDivision.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Items_IngredientDivision
	 * @param items_ingredientdivision
	 */
	public final void setItems_IngredientDivision(mainmodule.proxies.IngredientDivision items_ingredientdivision)
	{
		setItems_IngredientDivision(getContext(), items_ingredientdivision);
	}

	/**
	 * Set value of Items_IngredientDivision
	 * @param context
	 * @param items_ingredientdivision
	 */
	public final void setItems_IngredientDivision(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.IngredientDivision items_ingredientdivision)
	{
		if (items_ingredientdivision == null)
			getMendixObject().setValue(context, MemberNames.Items_IngredientDivision.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Items_IngredientDivision.toString(), items_ingredientdivision.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.Items that = (mainmodule.proxies.Items) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MainModule.Items";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
