// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class Recipe
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.Recipe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Uuid("Uuid"),
		Title("Title"),
		Yield("Yield"),
		Categories_Recipe("MainModule.Categories_Recipe"),
		Directions_Recipe("MainModule.Directions_Recipe"),
		Ingredients_Recipe("MainModule.Ingredients_Recipe");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Recipe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MainModule.Recipe"));
	}

	protected Recipe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject)
	{
		if (recipeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MainModule.Recipe", recipeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MainModule.Recipe");

		this.recipeMendixObject = recipeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Recipe.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mainmodule.proxies.Recipe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mainmodule.proxies.Recipe.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mainmodule.proxies.Recipe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.Recipe(context, mendixObject);
	}

	public static mainmodule.proxies.Recipe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.Recipe.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Uuid
	 */
	public final java.lang.String getUuid()
	{
		return getUuid(getContext());
	}

	/**
	 * @param context
	 * @return value of Uuid
	 */
	public final java.lang.String getUuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Uuid.toString());
	}

	/**
	 * Set value of Uuid
	 * @param uuid
	 */
	public final void setUuid(java.lang.String uuid)
	{
		setUuid(getContext(), uuid);
	}

	/**
	 * Set value of Uuid
	 * @param context
	 * @param uuid
	 */
	public final void setUuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.Uuid.toString(), uuid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Yield
	 */
	public final java.lang.Integer getYield()
	{
		return getYield(getContext());
	}

	/**
	 * @param context
	 * @return value of Yield
	 */
	public final java.lang.Integer getYield(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Yield.toString());
	}

	/**
	 * Set value of Yield
	 * @param yield
	 */
	public final void setYield(java.lang.Integer yield)
	{
		setYield(getContext(), yield);
	}

	/**
	 * Set value of Yield
	 * @param context
	 * @param yield
	 */
	public final void setYield(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yield)
	{
		getMendixObject().setValue(context, MemberNames.Yield.toString(), yield);
	}

	/**
	 * @return value of Categories_Recipe
	 */
	public final mainmodule.proxies.Categories getCategories_Recipe() throws com.mendix.core.CoreException
	{
		return getCategories_Recipe(getContext());
	}

	/**
	 * @param context
	 * @return value of Categories_Recipe
	 */
	public final mainmodule.proxies.Categories getCategories_Recipe(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Categories result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Categories_Recipe.toString());
		if (identifier != null)
			result = mainmodule.proxies.Categories.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Categories_Recipe
	 * @param categories_recipe
	 */
	public final void setCategories_Recipe(mainmodule.proxies.Categories categories_recipe)
	{
		setCategories_Recipe(getContext(), categories_recipe);
	}

	/**
	 * Set value of Categories_Recipe
	 * @param context
	 * @param categories_recipe
	 */
	public final void setCategories_Recipe(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Categories categories_recipe)
	{
		if (categories_recipe == null)
			getMendixObject().setValue(context, MemberNames.Categories_Recipe.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Categories_Recipe.toString(), categories_recipe.getMendixObject().getId());
	}

	/**
	 * @return value of Directions_Recipe
	 */
	public final mainmodule.proxies.Directions getDirections_Recipe() throws com.mendix.core.CoreException
	{
		return getDirections_Recipe(getContext());
	}

	/**
	 * @param context
	 * @return value of Directions_Recipe
	 */
	public final mainmodule.proxies.Directions getDirections_Recipe(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Directions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Directions_Recipe.toString());
		if (identifier != null)
			result = mainmodule.proxies.Directions.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Directions_Recipe
	 * @param directions_recipe
	 */
	public final void setDirections_Recipe(mainmodule.proxies.Directions directions_recipe)
	{
		setDirections_Recipe(getContext(), directions_recipe);
	}

	/**
	 * Set value of Directions_Recipe
	 * @param context
	 * @param directions_recipe
	 */
	public final void setDirections_Recipe(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Directions directions_recipe)
	{
		if (directions_recipe == null)
			getMendixObject().setValue(context, MemberNames.Directions_Recipe.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Directions_Recipe.toString(), directions_recipe.getMendixObject().getId());
	}

	/**
	 * @return value of Ingredients_Recipe
	 */
	public final mainmodule.proxies.Ingredients getIngredients_Recipe() throws com.mendix.core.CoreException
	{
		return getIngredients_Recipe(getContext());
	}

	/**
	 * @param context
	 * @return value of Ingredients_Recipe
	 */
	public final mainmodule.proxies.Ingredients getIngredients_Recipe(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mainmodule.proxies.Ingredients result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ingredients_Recipe.toString());
		if (identifier != null)
			result = mainmodule.proxies.Ingredients.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Ingredients_Recipe
	 * @param ingredients_recipe
	 */
	public final void setIngredients_Recipe(mainmodule.proxies.Ingredients ingredients_recipe)
	{
		setIngredients_Recipe(getContext(), ingredients_recipe);
	}

	/**
	 * Set value of Ingredients_Recipe
	 * @param context
	 * @param ingredients_recipe
	 */
	public final void setIngredients_Recipe(com.mendix.systemwideinterfaces.core.IContext context, mainmodule.proxies.Ingredients ingredients_recipe)
	{
		if (ingredients_recipe == null)
			getMendixObject().setValue(context, MemberNames.Ingredients_Recipe.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Ingredients_Recipe.toString(), ingredients_recipe.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recipeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.Recipe that = (mainmodule.proxies.Recipe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MainModule.Recipe";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
